name: Testovi

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koda
        uses: actions/checkout@v4

      - name: Podešavanje PHP-a
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, json, bcmath, curl, sqlite3
          coverage: none

      - name: Keš Composer zavisnosti
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Instalacija Composer zavisnosti
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Kopiranje .env fajla
        run: cp .env.example .env

      - name: Generisanje aplikacijskog ključa
        run: php artisan key:generate

      - name: Pokretanje testova
        run: php artisan test

